language: java

jdk:
  - openjdk8
  - oraclejdk8

branches:
  only:
    - master

sudo: required

before_install:
  - sudo apt update

install:
  - sudo apt install maven -y

before_script:
  - cd seip2019
  - ls -la

script:
  - mvn install  cobertura:cobertura

after_success:
- bash <(curl -s https://codecov.io/bash) -t fd5df06e-c96e-46aa-8fa0-99c1cd4b5da2
