language: java

jdk:
  - openjdk8
  - oraclejdk8

branches:
  only:
    - master

sudo: required

before_install:
  - sudo apt update

install:
  - sudo apt install maven -y

before_script:
  - cd seip2019
  - ls -la

script:
  - mvn install
